### 01. Importing libraries

In [1]:
import pandas as pd
import numpy as np
import os

### 02. Importing dataframe

In [3]:
ords_prods_merge = pd.read_pickle(r'C:\Users\veren\Python Data\26-10-2021 Instacart Basket Analysis\02 Data\Prepared Data\ords_prods_merge_GDAV.pkl')

### 03. Task 4.8

In [4]:
# Find the aggregated mean of the “order_number” column grouped by “department_id” for the entire dataframe.
ords_prods_merge.groupby('department_id').agg({'order_number':['mean']})

              order_number
                      mean
department_id
1                16.559161
2                18.413176
3                18.289622
4                18.915890
5                16.495614
6                17.609390
7                18.303969
8                16.383069
9                17.022963
10               21.227447
11               17.311920
12               16.953554
13               17.727257
14               17.882409
15               17.290123
16               18.755432
17               16.808683
18               20.336389
19               18.258620
20               17.578959
21               23.644477

The mean of the subset from the previous exercise and the mean of the whole dataset are very close. I think this makes sense because statistically the mean of the subset of the data can differ slightly from the whole, but it all should gravitate toward similar means.

In [5]:
# The marketing team at Instacart wants to know whether there's a difference between the spending habits of the three types of customers you identified. Use the loyalty flag you created and check the basic statistics of the product prices for each"
# What you're trying to determine is whether the prices of products purchased by loyal customers differ from those purchased by regular or new customers"
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.404557  1.0  99999.0
New customer      13.395978  1.0  99999.0
Regular customer  12.547284  1.0  99999.0

New customers and regular customers tend to spend more in the 13 US-Dollar prize range while loyal customers purchase products that range around 10 US-Dollar.

In [6]:
# Create a spending flag for each user based on the average price across all their orders using the following criteria:
# If the mean of the prices of products purchased by a user is lower than 10, then flag them as a “Low spender"
# If the mean of the prices of products purchased by a user is higher than or equal to 10, then flag them as a “High spender.”
ords_prods_merge['spending'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [7]:
ords_prods_merge.loc[ords_prods_merge['spending'] < 10, 'spending_flag'] = 'Low Spender'

In [8]:
ords_prods_merge.loc[ords_prods_merge['spending'] >= 10, 'spending_flag'] = 'High Spender'

In [9]:
# Pulling the data from the spending flag column
ords_prods_merge['spending_flag'].value_counts(dropna = False)

Low Spender     29756812
High Spender      599316
Name: spending_flag, dtype: int64

In [10]:
# Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column. 
# The criteria for the flag should be as follows:
# If the median of “days_since_prior_order” is higher than 20, then the customer should be labeled a “Non-frequent customer"
# If the median is higher than 10 and lower than or equal to 20, then the customer should be labeled a “Regular customer.”
# If the median is lower than or equal to 10, then the customer should be labeled a “Frequent customer.”
ords_prods_merge['frequency'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [11]:
ords_prods_merge.loc[ords_prods_merge['frequency'] > 20, 'frequency_flag'] = 'Non-frequent customer'

In [12]:
ords_prods_merge.loc[(ords_prods_merge['frequency'] <= 20) & (ords_prods_merge['frequency'] > 10), 'frequency_flag'] = 'Regular customer'

In [13]:
ords_prods_merge.loc[ords_prods_merge['frequency'] <= 10, 'frequency_flag'] = 'Frequent customer'

In [14]:
# Pulling the data from the frequency flag column
ords_prods_merge['frequency_flag'].value_counts(dropna = False)

Frequent customer        20692182
Regular customer          6602419
Non-frequent customer     3061527
Name: frequency_flag, dtype: int64

In [15]:
ords_prods_merge.head(10)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,order_dow,...,price_range_loc,busiest day,busiest days,busiest_period_of_day,max_order,loyalty_flag,spending,spending_flag,frequency,frequency_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,prior,28,6,...,Mid-range product,Regularly busy,Regularly busy,Most Orders,32,Regular customer,6.769286,Low Spender,8.0,Frequent customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,prior,30,6,...,Mid-range product,Regularly busy,Regularly busy,Most Orders,32,Regular customer,6.769286,Low Spender,8.0,Frequent customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,prior,2,0,...,Mid-range product,Busiest day,Busiest days,Average Orders,5,New customer,8.071613,Low Spender,8.0,Frequent customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,prior,3,4,...,Mid-range product,Least busy,Slowest days,Most Orders,3,New customer,4.864103,Low Spender,9.0,Frequent customer
4,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,prior,16,1,...,Mid-range product,Regularly busy,Busiest days,Average Orders,26,Regular customer,6.906422,Low Spender,11.0,Regular customer
5,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,prior,3,2,...,Mid-range product,Regularly busy,Regularly busy,Most Orders,9,New customer,6.086667,Low Spender,20.0,Regular customer
6,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,prior,12,3,...,Mid-range product,Regularly busy,Slowest days,Most Orders,12,Regular customer,6.800000,Low Spender,6.0,Frequent customer
7,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,prior,10,1,...,Mid-range product,Regularly busy,Busiest days,Average Orders,20,Regular customer,7.019149,Low Spender,10.0,Frequent customer
8,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,prior,15,1,...,Mid-range product,Regularly busy,Busiest days,Most Orders,20,Regular customer,7.019149,Low Spender,10.0,Frequent customer
9,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,prior,36,3,...,Mid-range product,Regularly busy,Slowest days,Most Orders,43,Loyal customer,5.163351,Low Spender,7.0,Frequent customer

In [17]:
# Exporting file as pkl
path = r'C:\Users\veren\Python Data\26-10-2021 Instacart Basket Analysis'

In [18]:
path

'C:\\Users\\veren\\Python Data\\26-10-2021 Instacart Basket Analysis'

In [19]:
ords_prods_merge.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge_GDAV_whole.pkl'))